apiVersion: v1
entries:
  qr-app:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-02-03T13:34:51.2433377+05:30"
    description: A Helm chart to deploy QR Code Generator Application
    digest: 241dd185d37724aa1c2d11eda0a8dba4c69221dfed4dfa53babb1d1b1fef26cb
    name: qr-app
    type: application
    urls:
    - qr-app-0.1.0.tgz
    version: 0.1.0
generated: "2026-02-03T13:34:51.2411622+05:30"
